import type { LinterConfigOverrideEntry } from '@standard-config/utilities/types';
import { configReactTestFiles } from '@standard-config/oxlint-react';
import mergeConfig from '@standard-config/utilities/merge-config';

const config: LinterConfigOverrideEntry = mergeConfig(configReactTestFiles, {
	rules: {
		'eslint/no-alert': 'off',
		'eslint/no-empty-function': 'off',
		'eslint/no-param-reassign': 'off',
		'eslint/no-promise-executor-return': 'off',
		'import/no-unassigned-import': 'off',
		'import/unambiguous': 'off',
		'jest/expect-expect': 'warn',
		'jest/no-commented-out-tests': 'warn',
		'jest/no-conditional-expect': 'error',
		'jest/no-conditional-in-test': 'error',
		'jest/no-confusing-set-timeout': 'error',
		'jest/no-deprecated-functions': 'error',
		'jest/no-disabled-tests': 'warn',
		'jest/no-duplicate-hooks': 'warn',
		'jest/no-export': 'error',
		'jest/no-focused-tests': 'warn',
		'jest/no-identical-title': 'warn',
		'jest/no-interpolation-in-snapshots': 'error',
		'jest/no-mocks-import': 'error',
		'jest/no-standalone-expect': 'error',
		'jest/no-test-return-statement': 'error',
		'jest/no-unneeded-async-expect-function': 'error',
		'jest/padding-around-after-all-blocks': 'error',
		'jest/padding-around-test-blocks': 'error',
		'jest/prefer-comparison-matcher': 'error',
		'jest/prefer-each': 'error',
		'jest/prefer-equality-matcher': 'error',
		'jest/prefer-expect-resolves': 'error',
		'jest/prefer-hooks-in-order': 'warn',
		'jest/prefer-hooks-on-top': 'warn',
		'jest/prefer-jest-mocked': 'error',
		'jest/prefer-mock-promise-shorthand': 'error',
		'jest/prefer-mock-return-shorthand': 'error',
		'jest/prefer-strict-equal': 'error',
		'jest/prefer-to-be': 'error',
		'jest/prefer-to-contain': 'error',
		'jest/prefer-to-have-been-called': 'error',
		'jest/prefer-to-have-been-called-times': 'error',
		'jest/prefer-to-have-length': 'error',
		'jest/prefer-todo': 'error',
		'jest/require-to-throw-message': 'error',
		'jest/valid-describe-callback': 'error',
		'jest/valid-expect': 'error',
		'jest/valid-title': 'error',
		'oxc/approx-constant': 'off',
		'oxc/no-accumulating-spread': 'off',
		'oxc/no-map-spread': 'off',
		'promise/catch-or-return': 'off',
		'promise/no-callback-in-promise': 'off',
		'promise/no-promise-in-callback': 'off',
		'promise/no-return-wrap': 'off',
		'promise/prefer-await-to-then': 'off',
		'typescript/ban-ts-comment': 'off',
		'typescript/explicit-module-boundary-types': 'off',
		'typescript/no-base-to-string': 'off',
		'typescript/no-confusing-void-expression': 'off',
		'typescript/no-extraneous-class': 'off',
		'typescript/no-restricted-types': 'off',
		'typescript/no-unsafe-argument': 'off',
		'typescript/no-unsafe-assignment': 'off',
		'typescript/no-unsafe-call': 'off',
		'typescript/no-unsafe-declaration-merging': 'off',
		'typescript/no-unsafe-enum-comparison': 'off',
		'typescript/no-unsafe-function-type': 'off',
		'typescript/no-unsafe-member-access': 'off',
		'typescript/no-unsafe-return': 'off',
		'typescript/no-unsafe-unary-minus': 'off',
		'typescript/only-throw-error': 'off',
		'typescript/restrict-template-expressions': 'off',
		'typescript/strict-void-return': 'off',
		'unicorn/consistent-function-scoping': 'off',
		'unicorn/error-message': 'off',
		'unicorn/no-empty-file': 'off',
		'unicorn/no-useless-promise-resolve-reject': 'off',
		'vitest/consistent-each-for': [
			'warn',
			{
				test: 'each',
				describe: 'each',
				it: 'each',
				suite: 'each',
			},
		],
		'vitest/consistent-vitest-vi': 'error',
		'vitest/hoisted-apis-on-top': 'error',
		'vitest/no-import-node-test': 'error',
		'vitest/prefer-called-times': 'error',
		'vitest/prefer-describe-function-title': 'error',
		'vitest/prefer-expect-type-of': 'error',
		'vitest/prefer-strict-boolean-matchers': 'error',
		'vitest/prefer-to-be-object': 'error',
		'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
		'vitest/require-test-timeout': 'off',
		'vitest/warn-todo': 'warn',
	},
});

export default config;
