packages:
  - packages/*

autoInstallPeers: false

catalog:
  '@eslint-react/eslint-plugin': ^5.18.1
  '@standard-config/tsconfig': ^3.2.0
  '@stylistic/eslint-plugin': ^5.10.0
  '@types/node': ^24.13.3
  eslint-plugin-perfectionist: ^5.10.0
  eslint-plugin-react-you-might-not-need-an-effect: ^1.0.1
  oxlint: ^1.76.0
  oxlint-tsgolint: ^7.0.2001
  publint: ^0.3.22
  typescript: ^6.0.3
  vite-plus: ^0.2.6

color: always

gitChecks: false

minimumReleaseAgeExclude:
  - '@oxlint/*'
  - '@oxlint-tsgolint/*'
  - '@standard-config/*'
  - oxlint
  - oxlint-tsgolint

overrides:
  vite-plus>oxfmt: '-'
  vite-plus>oxlint: 'catalog:'
  vite-plus>oxlint-tsgolint: 'catalog:'

peerDependencyRules:
  allowAny:
    - '@vitest/coverage-v8'

strictPeerDependencies: true

trustPolicy: no-downgrade

update:
  ignoreDeps:
    - '@types/node'
