packages:
  - packages/*

autoInstallPeers: false

catalog:
  '@standard-config/tsconfig': ^3.1.0
  oxlint: ^1.58.0
  oxlint-tsgolint: ^0.20.0
  publint: ^0.3.18
  typescript: ^6.0.2
  vite-plus: ^0.1.16-alpha.2
  vitest: ^4.1.2

color: always

gitChecks: false

onlyBuiltDependencies:
  - esbuild

overrides:
  vite-plus>oxfmt: '-'
  vite-plus>oxlint: 'catalog:'
  vite-plus>oxlint-tsgolint: 'catalog:'

peerDependencyRules:
  allowAny:
    - vitest

strictPeerDependencies: true

trustPolicy: no-downgrade

updateConfig:
  ignoreDependencies:
    - '@types/node'
