import type { LinterConfigEntry } from '../types/index.js';

const config: LinterConfigEntry = {
	plugins: [
		'eslint',
		'import',
		'jest',
		'node',
		'oxc',
		'promise',
		'typescript',
		'unicorn',
		'vitest',
	],
	categories: {
		correctness: 'error',
		pedantic: 'error',
		perf: 'error',
		restriction: 'error',
		style: 'error',
		suspicious: 'error',
	},
	env: {
		browser: true,
		node: true,
	},
	settings: {
		vitest: {
			typecheck: true,
		},
	},
	rules: {
		'eslint/accessor-pairs': ['error', { enforceForClassMembers: true }],
		'eslint/array-callback-return': ['error', { allowImplicit: true }],
		'eslint/arrow-body-style': 'off',
		'eslint/capitalized-comments': 'off',
		'eslint/func-names': 'off',
		'eslint/func-style': [
			'error',
			'declaration',
			{ allowArrowFunctions: true },
		],
		'eslint/grouped-accessor-pairs': ['error', 'getBeforeSet'],
		'eslint/id-length': 'off',
		'eslint/init-declarations': 'off',
		'eslint/max-depth': 'off',
		'eslint/max-lines': 'off',
		'eslint/max-lines-per-function': 'off',
		'eslint/max-params': 'off',
		'eslint/max-statements': 'off',
		'eslint/new-cap': 'off',
		'eslint/no-await-in-loop': 'off',
		'eslint/no-continue': 'off',
		'eslint/no-duplicate-imports': 'off',
		'eslint/no-else-return': ['error', { allowElseIf: false }],
		'eslint/no-empty': ['error', { allowEmptyCatch: true }],
		'eslint/no-empty-function': 'warn',
		'eslint/no-inline-comments': 'off',
		'eslint/no-magic-numbers': 'off',
		'eslint/no-return-assign': ['error', 'always'],
		'eslint/no-self-assign': ['error', { props: true }],
		'eslint/no-shadow': 'off',
		'eslint/no-ternary': 'off',
		'eslint/no-undefined': 'off',
		'eslint/no-unsafe-negation': [
			'error',
			{ enforceForOrderingRelations: true },
		],
		'eslint/no-unsafe-optional-chaining': [
			'error',
			{ disallowArithmeticOperators: true },
		],
		'eslint/no-unused-expressions': ['error', { enforceForJSX: true }],
		'eslint/no-unused-vars': [
			'warn',
			{
				argsIgnorePattern: '^_',
				caughtErrorsIgnorePattern: '^_',
				destructuredArrayIgnorePattern: '^_',
				varsIgnorePattern: '^_',
			},
		],
		'eslint/no-use-before-define': 'off',
		'eslint/no-void': 'off',
		'eslint/prefer-destructuring': [
			'error',
			{ enforceForRenamedProperties: false },
		],
		'eslint/prefer-promise-reject-errors': 'off',
		'eslint/require-await': 'off',
		'eslint/sort-imports': 'off',
		'eslint/sort-keys': 'off',
		'eslint/valid-typeof': ['error', { requireStringLiterals: false }],
		'import/exports-last': 'off',
		'import/group-exports': 'off',
		'import/max-dependencies': 'off',
		'import/no-default-export': 'off',
		'import/no-named-export': 'off',
		'import/no-namespace': 'off',
		'import/no-nodejs-modules': 'off',
		'import/no-relative-parent-imports': 'off',
		'import/prefer-default-export': 'off',
		'import/unambiguous': 'warn',
		'jest/consistent-test-it': 'off',
		'jest/max-expects': 'off',
		'jest/max-nested-describe': 'off',
		'jest/no-alias-methods': 'off',
		'jest/no-done-callback': 'off',
		'jest/no-hooks': 'off',
		'jest/no-jasmine-globals': 'off',
		'jest/no-large-snapshots': 'off',
		'jest/no-restricted-jest-methods': 'off',
		'jest/no-restricted-matchers': 'off',
		'jest/no-test-prefixes': 'off',
		'jest/no-untyped-mock-factory': 'off',
		'jest/prefer-called-with': 'off',
		'jest/prefer-lowercase-title': 'off',
		'jest/prefer-spy-on': 'off',
		'jest/require-hook': 'off',
		'jest/require-top-level-describe': 'off',
		'node/no-process-env': 'off',
		'oxc/approx-constant': 'error',
		'oxc/branches-sharing-code': 'warn',
		'oxc/const-comparisons': 'warn',
		'oxc/no-accumulating-spread': 'error',
		'oxc/no-async-await': 'off',
		'oxc/no-async-endpoint-handlers': 'off',
		'oxc/no-barrel-file': 'off',
		'oxc/no-const-enum': 'off',
		'oxc/no-map-spread': 'error',
		'oxc/no-optional-chaining': 'off',
		'oxc/no-rest-spread-properties': 'off',
		'promise/avoid-new': 'off',
		'promise/prefer-await-to-callbacks': 'off',
		'typescript/array-type': [
			'error',
			{
				default: 'array-simple',
				readonly: 'generic',
			},
		],
		'typescript/ban-ts-comment': [
			'error',
			{
				'ts-check': true,
				'ts-expect-error': false,
				'ts-ignore': true,
				'ts-nocheck': true,
			},
		],
		'typescript/consistent-type-definitions': ['error', 'type'],
		'typescript/consistent-type-imports': [
			'error',
			{
				fixStyle: 'separate-type-imports',
				prefer: 'type-imports',
			},
		],
		'typescript/explicit-function-return-type': 'off',
		'typescript/no-confusing-void-expression': [
			'error',
			{ ignoreArrowShorthand: true },
		],
		'typescript/no-deprecated': 'warn',
		'typescript/no-empty-interface': 'off',
		'typescript/no-explicit-any': 'off',
		'typescript/no-misused-promises': [
			'error',
			{
				checksConditionals: true,
				checksVoidReturn: false,
			},
		],
		'typescript/no-namespace': ['error', { allowDeclarations: true }],
		'typescript/no-non-null-assertion': 'off',
		'typescript/no-restricted-types': [
			'error',
			{
				types: {
					'[]': true,
					'null': true,
					'object': true,
				},
			},
		],
		'typescript/no-unsafe-type-assertion': 'off',
		'typescript/only-throw-error': [
			'error',
			{
				allowThrowingAny: false,
				allowThrowingUnknown: true,
			},
		],
		'typescript/prefer-nullish-coalescing': [
			'error',
			{ ignoreConditionalTests: false },
		],
		'typescript/prefer-promise-reject-errors': 'off',
		'typescript/prefer-readonly-parameter-types': 'off',
		'typescript/require-array-sort-compare': [
			'error',
			{ ignoreStringArrays: true },
		],
		'typescript/require-await': 'warn',
		'typescript/restrict-template-expressions': [
			'error',
			{ allowNumber: true },
		],
		'typescript/strict-boolean-expressions': 'off',
		'typescript/switch-exhaustiveness-check': [
			'error',
			{
				allowDefaultCaseForExhaustiveSwitch: false,
				considerDefaultExhaustiveForUnions: true,
				requireDefaultForNonUnion: true,
			},
		],
		'typescript/unbound-method': 'off',
		'unicorn/catch-error-name': 'error',
		'unicorn/consistent-assert': 'error',
		'unicorn/consistent-date-clone': 'error',
		'unicorn/consistent-empty-array-spread': 'error',
		'unicorn/consistent-existence-index-check': 'error',
		'unicorn/consistent-function-scoping': 'error',
		'unicorn/empty-brace-spaces': 'error',
		'unicorn/error-message': 'error',
		'unicorn/escape-case': 'error',
		'unicorn/explicit-length-check': 'error',
		'unicorn/filename-case': 'off',
		'unicorn/new-for-builtins': 'error',
		'unicorn/no-abusive-eslint-disable': 'error',
		'unicorn/no-accessor-recursion': 'error',
		'unicorn/no-anonymous-default-export': 'error',
		'unicorn/no-array-callback-reference': 'off',
		'unicorn/no-array-for-each': 'error',
		'unicorn/no-array-method-this-argument': 'error',
		'unicorn/no-array-reduce': 'error',
		'unicorn/no-array-reverse': 'error',
		'unicorn/no-array-sort': ['error'],
		'unicorn/no-await-expression-member': 'error',
		'unicorn/no-await-in-promise-methods': 'error',
		'unicorn/no-console-spaces': 'error',
		'unicorn/no-document-cookie': 'error',
		'unicorn/no-empty-file': 'warn',
		'unicorn/no-hex-escape': 'error',
		'unicorn/no-immediate-mutation': 'error',
		'unicorn/no-instanceof-array': 'error',
		'unicorn/no-instanceof-builtins': 'error',
		'unicorn/no-invalid-fetch-options': 'error',
		'unicorn/no-invalid-remove-event-listener': 'error',
		'unicorn/no-length-as-slice-end': 'error',
		'unicorn/no-lonely-if': 'error',
		'unicorn/no-magic-array-flat-depth': 'error',
		'unicorn/no-negation-in-equality-check': 'error',
		'unicorn/no-nested-ternary': 'error',
		'unicorn/no-new-array': 'error',
		'unicorn/no-new-buffer': 'error',
		'unicorn/no-null': 'off',
		'unicorn/no-object-as-default-parameter': 'error',
		'unicorn/no-process-exit': 'error',
		'unicorn/no-single-promise-in-promise-methods': 'off',
		'unicorn/no-static-only-class': 'error',
		'unicorn/no-thenable': 'error',
		'unicorn/no-this-assignment': 'error',
		'unicorn/no-typeof-undefined': [
			'error',
			{ checkGlobalVariables: true },
		],
		'unicorn/no-unnecessary-array-flat-depth': 'error',
		'unicorn/no-unnecessary-array-splice-count': 'error',
		'unicorn/no-unnecessary-await': 'error',
		'unicorn/no-unnecessary-slice-end': 'error',
		'unicorn/no-unreadable-array-destructuring': 'error',
		'unicorn/no-unreadable-iife': 'error',
		'unicorn/no-useless-collection-argument': 'error',
		'unicorn/no-useless-error-capture-stack-trace': 'error',
		'unicorn/no-useless-fallback-in-spread': 'error',
		'unicorn/no-useless-length-check': 'error',
		'unicorn/no-useless-promise-resolve-reject': 'error',
		'unicorn/no-useless-spread': 'error',
		'unicorn/no-useless-switch-case': 'error',
		'unicorn/no-useless-undefined': 'off',
		'unicorn/no-zero-fractions': 'error',
		'unicorn/number-literal-case': 'error',
		'unicorn/numeric-separators-style': [
			'error',
			{ onlyIfContainsSeparator: true },
		],
		'unicorn/prefer-add-event-listener': 'error',
		'unicorn/prefer-array-find': 'error',
		'unicorn/prefer-array-flat': 'error',
		'unicorn/prefer-array-flat-map': 'error',
		'unicorn/prefer-array-index-of': 'error',
		'unicorn/prefer-array-some': 'error',
		'unicorn/prefer-at': 'error',
		'unicorn/prefer-bigint-literals': 'off',
		'unicorn/prefer-blob-reading-methods': 'error',
		'unicorn/prefer-class-fields': 'error',
		'unicorn/prefer-classlist-toggle': 'error',
		'unicorn/prefer-code-point': 'error',
		'unicorn/prefer-date-now': 'error',
		'unicorn/prefer-default-parameters': 'error',
		'unicorn/prefer-dom-node-append': 'error',
		'unicorn/prefer-dom-node-dataset': 'error',
		'unicorn/prefer-dom-node-remove': 'error',
		'unicorn/prefer-dom-node-text-content': 'error',
		'unicorn/prefer-event-target': 'error',
		'unicorn/prefer-global-this': 'error',
		'unicorn/prefer-includes': 'error',
		'unicorn/prefer-keyboard-event-key': 'error',
		'unicorn/prefer-logical-operator-over-ternary': 'error',
		'unicorn/prefer-math-min-max': 'error',
		'unicorn/prefer-math-trunc': 'error',
		'unicorn/prefer-modern-dom-apis': 'error',
		'unicorn/prefer-modern-math-apis': 'error',
		'unicorn/prefer-module': 'error',
		'unicorn/prefer-native-coercion-functions': 'error',
		'unicorn/prefer-negative-index': 'error',
		'unicorn/prefer-node-protocol': 'error',
		'unicorn/prefer-number-properties': [
			'error',
			{
				checkInfinity: true,
				checkNaN: true,
			},
		],
		'unicorn/prefer-object-from-entries': 'error',
		'unicorn/prefer-optional-catch-binding': 'error',
		'unicorn/prefer-prototype-methods': 'error',
		'unicorn/prefer-query-selector': 'error',
		'unicorn/prefer-reflect-apply': 'error',
		'unicorn/prefer-regexp-test': 'error',
		'unicorn/prefer-response-static-json': 'error',
		'unicorn/prefer-set-has': 'error',
		'unicorn/prefer-set-size': 'error',
		'unicorn/prefer-spread': 'error',
		'unicorn/prefer-string-raw': 'error',
		'unicorn/prefer-string-replace-all': 'error',
		'unicorn/prefer-string-slice': 'error',
		'unicorn/prefer-string-starts-ends-with': 'error',
		'unicorn/prefer-string-trim-start-end': 'error',
		'unicorn/prefer-structured-clone': 'off',
		'unicorn/prefer-ternary': ['error', 'always'],
		'unicorn/prefer-top-level-await': 'error',
		'unicorn/prefer-type-error': 'error',
		'unicorn/relative-url-style': ['error', 'never'],
		'unicorn/require-array-join-separator': 'error',
		'unicorn/require-module-attributes': 'error',
		'unicorn/require-module-specifiers': 'error',
		'unicorn/require-number-to-fixed-digits-argument': 'error',
		'unicorn/require-post-message-target-origin': 'error',
		'unicorn/switch-case-braces': ['error', 'avoid'],
		'unicorn/text-encoding-identifier-case': 'error',
		'unicorn/throw-new-error': 'error',
		'vitest/consistent-test-filename': 'off',
		'vitest/no-conditional-tests': 'off',
		'vitest/no-importing-vitest-globals': 'off',
		'vitest/no-restricted-vi-methods': 'off',
		'vitest/prefer-called-once': 'off',
		'vitest/prefer-import-in-mock': 'off',
		'vitest/prefer-to-be-falsy': 'off',
		'vitest/prefer-to-be-truthy': 'off',
	},
};

export default config;
