import type { LinterConfigOverrideEntry } from '../types/index.d.ts';

const config: LinterConfigOverrideEntry = {
	plugins: ['jsx-a11y', 'react', 'react-perf'],
	rules: {
		'jsx-a11y/alt-text': 'error',
		'jsx-a11y/anchor-ambiguous-text': 'error',
		'jsx-a11y/anchor-has-content': 'error',
		'jsx-a11y/anchor-is-valid': 'error',
		'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
		'jsx-a11y/aria-props': 'error',
		'jsx-a11y/aria-proptypes': 'error',
		'jsx-a11y/aria-role': 'error',
		'jsx-a11y/aria-unsupported-elements': 'error',
		'jsx-a11y/autocomplete-valid': 'error',
		'jsx-a11y/click-events-have-key-events': 'warn',
		'jsx-a11y/heading-has-content': 'error',
		'jsx-a11y/html-has-lang': 'error',
		'jsx-a11y/iframe-has-title': 'error',
		'jsx-a11y/img-redundant-alt': 'off',
		'jsx-a11y/label-has-associated-control': 'error',
		'jsx-a11y/lang': 'error',
		'jsx-a11y/media-has-caption': 'off',
		'jsx-a11y/mouse-events-have-key-events': 'warn',
		'jsx-a11y/no-access-key': 'error',
		'jsx-a11y/no-aria-hidden-on-focusable': 'error',
		'jsx-a11y/no-autofocus': 'error',
		'jsx-a11y/no-distracting-elements': 'error',
		'jsx-a11y/no-noninteractive-tabindex': 'error',
		'jsx-a11y/no-redundant-roles': 'error',
		'jsx-a11y/no-static-element-interactions': 'error',
		'jsx-a11y/prefer-tag-over-role': 'error',
		'jsx-a11y/role-has-required-aria-props': 'error',
		'jsx-a11y/role-supports-aria-props': 'error',
		'jsx-a11y/scope': 'error',
		'jsx-a11y/tabindex-no-positive': 'error',
		'react-perf/jsx-no-jsx-as-prop': 'off',
		'react-perf/jsx-no-new-array-as-prop': 'error',
		'react-perf/jsx-no-new-function-as-prop': 'off',
		'react-perf/jsx-no-new-object-as-prop': 'off',
		'react/button-has-type': 'error',
		'react/checked-requires-onchange-or-readonly': 'error',
		'react/display-name': 'off',
		'react/exhaustive-deps': 'error',
		'react/forbid-dom-props': 'off',
		'react/forbid-elements': 'off',
		'react/forward-ref-uses-ref': 'off',
		'react/iframe-missing-sandbox': 'off',
		'react/jsx-boolean-value': 'error',
		'react/jsx-curly-brace-presence': [
			'error',
			{
				children: 'never',
				propElementValues: 'always',
				props: 'never',
			},
		],
		'react/jsx-filename-extension': ['error', { extensions: ['.tsx'] }],
		'react/jsx-fragments': 'error',
		'react/jsx-handler-names': 'error',
		'react/jsx-key': 'error',
		'react/jsx-max-depth': 'off',
		'react/jsx-no-comment-textnodes': 'error',
		'react/jsx-no-constructed-context-values': 'error',
		'react/jsx-no-duplicate-props': 'error',
		'react/jsx-no-script-url': 'error',
		'react/jsx-no-target-blank': [
			'error',
			{ warnOnSpreadAttributes: true },
		],
		'react/jsx-no-undef': 'error',
		'react/jsx-no-useless-fragment': 'error',
		'react/jsx-pascal-case': 'error',
		'react/jsx-props-no-spread-multi': 'error',
		'react/jsx-props-no-spreading': 'off',
		'react/no-array-index-key': 'error',
		'react/no-children-prop': 'error',
		'react/no-danger': 'error',
		'react/no-danger-with-children': 'error',
		'react/no-did-mount-set-state': 'off',
		'react/no-direct-mutation-state': 'off',
		'react/no-find-dom-node': 'off',
		'react/no-is-mounted': 'off',
		'react/no-multi-comp': 'off',
		'react/no-namespace': 'error',
		'react/no-redundant-should-component-update': 'off',
		'react/no-render-return-value': 'off',
		'react/no-set-state': 'off',
		'react/no-string-refs': 'off',
		'react/no-this-in-sfc': 'off',
		'react/no-unescaped-entities': 'error',
		'react/no-unknown-property': 'error',
		'react/no-unsafe': 'off',
		'react/no-will-update-set-state': 'off',
		'react/only-export-components': 'off',
		'react/prefer-es6-class': 'off',
		'react/react-in-jsx-scope': 'off',
		'react/require-render-return': 'off',
		'react/rules-of-hooks': 'error',
		'react/self-closing-comp': 'error',
		'react/state-in-constructor': 'off',
		'react/style-prop-object': 'error',
		'react/void-dom-elements-no-children': 'error',
	},
};

export default config;
