import type { LinterConfigOverrideEntry } from '../types/index.d.ts';

const config: LinterConfigOverrideEntry = {
	rules: {
		'eslint/no-alert': 'off',
		'eslint/no-param-reassign': 'off',
		'eslint/no-promise-executor-return': 'off',
		'import/no-unassigned-import': 'off',
		'import/unambiguous': 'off',
		'jest/expect-expect': 'warn',
		'jest/no-commented-out-tests': 'warn',
		'jest/no-conditional-expect': 'error',
		'jest/no-conditional-in-test': 'error',
		'jest/no-confusing-set-timeout': 'error',
		'jest/no-deprecated-functions': 'error',
		'jest/no-disabled-tests': 'warn',
		'jest/no-duplicate-hooks': 'warn',
		'jest/no-export': 'error',
		'jest/no-focused-tests': 'warn',
		'jest/no-identical-title': 'warn',
		'jest/no-interpolation-in-snapshots': 'error',
		'jest/no-mocks-import': 'error',
		'jest/no-standalone-expect': 'error',
		'jest/no-test-return-statement': 'error',
		'jest/no-unneeded-async-expect-function': 'error',
		'jest/no-untyped-mock-factory': 'error',
		'jest/padding-around-test-blocks': 'error',
		'jest/prefer-comparison-matcher': 'error',
		'jest/prefer-each': 'error',
		'jest/prefer-equality-matcher': 'error',
		'jest/prefer-expect-resolves': 'error',
		'jest/prefer-hooks-in-order': 'warn',
		'jest/prefer-hooks-on-top': 'warn',
		'jest/prefer-jest-mocked': 'error',
		'jest/prefer-mock-promise-shorthand': 'error',
		'jest/prefer-mock-return-shorthand': 'error',
		'jest/prefer-strict-equal': 'error',
		'jest/prefer-to-be': 'error',
		'jest/prefer-to-contain': 'error',
		'jest/prefer-to-have-been-called': 'error',
		'jest/prefer-to-have-been-called-times': 'error',
		'jest/prefer-to-have-length': 'error',
		'jest/prefer-todo': 'error',
		'jest/require-to-throw-message': 'error',
		'jest/valid-describe-callback': 'error',
		'jest/valid-expect': 'error',
		'jest/valid-title': 'error',
		'jsx-a11y/anchor-is-valid': 'off',
		'jsx-a11y/click-events-have-key-events': 'off',
		'jsx-a11y/mouse-events-have-key-events': 'off',
		'promise/prefer-await-to-then': 'off',
		'react-perf/jsx-no-new-array-as-prop': 'off',
		'react/button-has-type': 'off',
		'react/checked-requires-onchange-or-readonly': 'off',
		'react/jsx-no-useless-fragment': 'off',
		'react/no-array-index-key': 'off',
		'react/no-children-prop': 'off',
		'react/no-danger': 'off',
		'typescript/ban-ts-comment': 'off',
		'typescript/no-confusing-void-expression': 'off',
		'typescript/no-empty-function': 'off',
		'typescript/no-extraneous-class': 'off',
		'typescript/no-unsafe-argument': 'off',
		'typescript/no-unsafe-assignment': 'off',
		'typescript/no-unsafe-member-access': 'off',
		'typescript/strict-void-return': 'off',
		'unicorn/consistent-function-scoping': 'off',
		'unicorn/error-message': 'off',
		'unicorn/no-empty-file': 'off',
		'vitest/consistent-each-for': [
			'warn',
			{
				describe: 'each',
				it: 'each',
				suite: 'each',
				test: 'each',
			},
		],
		'vitest/consistent-vitest-vi': 'error',
		'vitest/hoisted-apis-on-top': 'error',
		'vitest/no-import-node-test': 'error',
		'vitest/prefer-called-times': 'error',
		'vitest/prefer-describe-function-title': 'error',
		'vitest/prefer-expect-type-of': 'error',
		'vitest/prefer-to-be-object': 'error',
		'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
		'vitest/warn-todo': 'warn',
	},
};

export default config;
