import type { LinterConfigOverrideEntry } from '../types/index.d.ts';

const config: LinterConfigOverrideEntry = {
	rules: {
		'eslint/no-alert': 'off',
		'eslint/no-param-reassign': 'off',
		'eslint/no-promise-executor-return': 'off',
		'eslint/no-shadow': 'off',
		'import/no-unassigned-import': 'off',
		'import/unambiguous': 'off',
		'jsx-a11y/anchor-is-valid': 'off',
		'promise/prefer-await-to-then': 'off',
		'react/jsx-no-useless-fragment': 'off',
		'react/no-children-prop': 'off',
		'typescript/ban-ts-comment': 'off',
		'typescript/no-confusing-void-expression': 'off',
		'typescript/no-empty-function': 'off',
		'typescript/no-extraneous-class': 'off',
		'typescript/no-unsafe-argument': 'off',
		'typescript/no-unsafe-assignment': 'off',
		'typescript/no-unsafe-member-access': 'off',
		'unicorn/consistent-function-scoping': 'off',
		'unicorn/error-message': 'off',
		'unicorn/no-empty-file': 'off',
		'vitest/consistent-test-it': 'off',
		'vitest/max-expects': 'off',
		'vitest/max-nested-describe': 'off',
		'vitest/no-alias-methods': 'off',
		'vitest/no-conditional-tests': 'off',
		'vitest/no-disabled-tests': 'warn',
		'vitest/no-hooks': 'off',
		'vitest/no-large-snapshots': 'off',
		'vitest/prefer-called-once': 'off',
		'vitest/prefer-called-with': 'off',
		'vitest/prefer-lowercase-title': 'off',
		'vitest/prefer-spy-on': 'off',
		'vitest/prefer-to-be-falsy': 'off',
		'vitest/prefer-to-be-truthy': 'off',
		'vitest/require-top-level-describe': 'off',
	},
};

export default config;
